spring:
  profiles:
    active: console, database, service, actuators
  application:
    name: auth

server:
  port: ${SERVER_PORT:8000}
  address: ${SERVER_ADDRESS:localhost}
  servlet:
    context-path: /api