spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:example}?ssl=true&sslmode=require 
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver 
    hikari:
      #connection-timeout: 30000
      #maximum-pool-size: 10
      #minimum-idle: 2
      #idle-timeout: 600000
      #max-lifetime: 1800000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false 
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
