spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:example}?ssl=true&sslmode=require 
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver 
    hikari:
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false 
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASSWORD}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:testdb}
