spring:
  datasource:
    hikari:
      keepalive-time: 100000
      max-lifetime: 1800000
      idle-timeout: 600000
      minimum-idle: 5
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

